[platformio]
src_dir = Core/Src
include_dir = Core/Inc
default_envs = blackpill_f411ce

[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = stm32cube
build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F411xE
    -ICore/Inc
    -Wl,-u,_printf_float
board_build.ldscript = STM32F411CEU6_FLASH.ld
monitor_speed = 115200
upload_protocol = stlink
